// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFtSVhNXTsyTdLwaI95oO9BdtjgeQQyI',
    appId: '1:643971624111:android:23be2f8933f4c28213385a',
    messagingSenderId: '643971624111',
    projectId: 'bridge-0909',
    storageBucket: 'bridge-0909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDoF-85r8fRqJRKGjSlI0gTsV3c_iIPuY',
    appId: '1:643971624111:ios:022e7427aa79608213385a',
    messagingSenderId: '643971624111',
    projectId: 'bridge-0909',
    storageBucket: 'bridge-0909.appspot.com',
    androidClientId: '643971624111-fmo10v909jdrdscn2s7qpgn6m35mi963.apps.googleusercontent.com',
    iosClientId: '643971624111-4482u3gdecrf6lgfsujh8nlaue6mnd9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridge',
  );

}